# https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://mhu.dev"
title = "mhu.dev"
description = "DevOoops"

build_search_index = false
compile_sass = true
default_language = "en"
minify_html = true

taxonomies = [{name = "tags"}]

[markdown]
highlight_code = true
render_emoji = true

[link_checker]
skip_prefixes = [
  "https://www.linkedin.com/"
]

[slugify]
paths_keep_dates = true

[extra]
# Number of posts to display on the home page
homepage_posts = 5
author = "Manuel Hutter"
